// AUTH ACTIONS TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// MODEL ACTIONS TYPES
export const GET_ALL_MODELS_REQUEST = 'GET_ALL_MODELS_REQUEST';
export const GET_ALL_MODELS_SUCCESS = 'GET_ALL_MODELS_SUCCESS';
export const GET_ALL_MODELS_FAIL = 'GET_ALL_MODELS_FAIL';